### ISSUE TITLE
Field type "file" is not save correctly

### ISSUE THREAD

**Issue by thomasfahrland** [TimOetting/kirby-v3-builder#10]
When saving a build section, the content of a file field is not stored in the content txt file as in Kirby standard. Actually this plugin is saving many other infos instead of only the filename. 

.yml config:
[config.yml.txt](https://github.com/TimOetting/kirby-v3-builder/files/2633486/config.yml.txt)

Result:
![result](https://user-images.githubusercontent.com/24317084/49293988-fb75f300-f4b1-11e8-9b3c-da4779166b19.png)

**Comment by sylvainjule** [comment]
This is also applicable to the Pages field.

From what I get the builder is grabbing the `value` of vue components within its blocks and saves it directly, whereas Kirby's update process has been refactored and now checks the field's id against its stored value, stored in `$store.state.form.models['page-id'].values`, and saves only parts of it if it has changed. 

I believe it started with [this commit](https://github.com/k-next/kirby/commit/9a5b5e6b6d383fbf67652fe05e6f52168f364303) but I'm not sure where to pinpoint this exactly, better ask @distantnative.

Files fields store an array of images' `filename`:
```
myimages:
  - image-01.jpg
  - image-02.jpg
```

Pages fields store an array of pages' `id`:
```
mypages:
  - path/to/page
  - path/to/another-page
```

**Comment by sylvainjule** [comment]
To get around it for now when using the field in your templates you can add some `fieldMethods` setting the array correctly before converting the fields:

```
'fieldMethods' => [
    'toBuilderFiles' => function($field) {
        $ids = array_map(function($field) {
            return $field['filename'];
        }, $field->value());
        $field->value = Yaml::encode($ids);
        return $field;
    },
    'toBuilderPages' => function($field) {
        $ids = array_map(function($field) {
            return $field['id'];
        }, $field->value());
        $field->value = Yaml::encode($ids);
        return $field;
    }
],
```

And then use `$field->toBuilderFiles()->toFiles()`.
This way when it gets fixed, you'll only have to delete the method part.

**Comment by thomasfahrland** [comment]
sylvainjule thanks for the workaround, works! :)

**Comment by TimOetting** [comment]
The current commit fixed this issue. Files and pages should now be saved in the correct structure
