### ISSUE TITLE
Can't create new pages where the template use the builder field type

### ISSUE THREAD

**Issue by kaloja** [TimOetting/kirby-v3-builder#18]
When trying to create a new page, which using the builder plugin I get: `Invalid argument supplied for foreach()`.

I managed to work around it, when adding the following code snippet to the save function. I don't know if this is the best approach to solve the bug, but it works.

```
'save' => function ($values = null) {
        $values = Yaml::decode($this->value);
}
```

**Comment by TimOetting** [comment]
Hey @kaloja . The repository has been moved to https://github.com/TimOetting/kirby-builder/ . Your problem should be fixed with the latest version.
