### ISSUE TITLE
Structure field inside builder doesn't work

### ISSUE THREAD

**Issue by olach** [TimOetting/kirby-v3-builder#19]
When using a structure field as a field inside this builder plugin, an error occurs.

    undefined is not an object (evaluating 't.endpoints.field')

This error seems to started happening after this commit in Kirby Core:

https://github.com/k-next/kirby/commit/d4ed1fdf1fd71b61a6ee7e59ccaa03fc968a7247#diff-52f37d338d34e955e9e0b5e5aad44e8f

I tried to figure out the cause for this, but my PHP/JS skills are not that good unfortunately.

**Comment by olach** [comment]
Kirby 3 Nightly build 2018-12-12 works. After that version, a change in Kirby Core makes the Structure field incompatible with the builder plugin.

**Comment by olach** [comment]
I just updated to the Kirby RC1 released today. Now the core `files field` doesn't work inside the builder plugin. I get the same error message as above, but not printed on the screen, only in the dev console.

So I guess there were some changes in the core that your builder plugin needs to support?

**Comment by jschopplich** [comment]
@TimOetting Any update on this issue? 🙂

**Comment by TimOetting** [comment]
Hey. The repository has been moved to https://github.com/TimOetting/kirby-builder/ . The latest version works with structure fields again (and also with files and pages fields)
