### ISSUE TITLE
Field  type: files dont work

### ISSUE THREAD

**Issue by 53b1** [TimOetting/kirby-v3-builder#21]
On Version 3.0.0-RC-1.0 and higher i can´t select any Files.
I get this Error: "Cannot read property 'field' of undefined"
![bildschirmfoto 2018-12-21 um 11 54 15](https://user-images.githubusercontent.com/32280392/50339233-300c2600-0517-11e9-94d0-138e120a503b.png)

**Comment by mcbrwr** [comment]
this might be fixed with this PR: https://github.com/TimOetting/kirby-v3-builder/pull/23
if you can test this, it would be much appreciated! :)

**Comment by seehat** [comment]
This fix works for me. Thx. :)

**Comment by mcbrwr** [comment]
I found another little bug with this setup when a “pages” field was used. fixing it asap.

;-) Matthijs

**Comment by TimOetting** [comment]
The repository has been moved to https://github.com/TimOetting/kirby-builder/ . The current version solved all the issues with files, structure and pages fields.
