### ISSUE TITLE
Sorting is not working anymore. 

### ISSUE THREAD

**Issue by seehat** [TimOetting/kirby-v3-builder#24]
When I start to drag an item the following error occurs:

Cannot read property 'item' of undefined

**Comment by idrisyangui** [comment]
I get similar issu when dragging block : 
`undefined is not an object (evaluating 't.item')`

**Comment by TimOetting** [comment]
This repository has been moved to https://github.com/TimOetting/kirby-builder/ . I solved the sorting issue with the latest version.
