### ISSUE TITLE
The field type does not exist 

### ISSUE THREAD

**Issue by H-i-red** [TimOetting/kirby-v3-builder#4]
Hi I get `The field type "mybuilder" does not exist` !? (Beta 6)

**Comment by TimOetting** [comment]
@sylvainjule thanks for pointing me to that issue. I made that experience as well when I ran two plugins in my local setup but did not relaize that I forgot to run the correct build before pushing the last commit. I will need to have a closer look at the build pipeline to avoid this issue in the future
