### ISSUE TITLE
[Feature Request] Add Options to Finely Control Number of Blocks - Overall and by Type

### ISSUE THREAD

**Issue by luxlogica** [TimOetting/kirby-v3-builder#9]
## Use-Case: Landing Page Sections
We want to be able to allow the client to add Landing Pages to their site. Each Landing Page is going to be structured like this:

- an obligatory **Hero Banner** at the top of the page - this always has to be present, and there can be only 1 Hero Banner
- a number of optional **Info Sections** - some landing pages may have no Info Sections, some may have 3 or 4, of different types and layouts, in different orders.
- an optional **Contact Section** - some landing pages may have a Contact Section, some may not. But if a Contact Section is present, there should be only 1 on the page.

## Issue: Hero Banner is Deletable
At the moment, we can setup an interface - using Kirby Builder - for editing the 'Info Sections', and the 'Contact' section, without trouble. The 'Info Sections' are just a normal builder field. In order to setup the 'Contact' section, we can setup a builder field with a `limit: 1` option, and that would work fine: we'll be able to add a Contact Section when needed, but not more than 1, and we'll be able to delete it when it shouldn't be on the page.

The issue is the Hero Banner: we can set it with a `limit: 1`, like the Contact Section, but there is no current way to *stop it from being deleted*. This is not an _optional_ section, like Contact, and it should be present on every page - so the user should never be able to delete it.

#### 1) Simple: add a `deletable: false` option to the fieldset
This would make blocks created from a certain fieldset _permanent_ - ie., not deletable. Using this, we could get what we want by simply making the Hero Banner fieldset use `deletable: false`, while at the same time setting the builder field's `limit: 1`. 

#### 2) Flexible: add `max:` and `min:` options to the fieldset
Instead of making all blocks of a certain type un-deletable, we could add options that set out that there should be a minimum and maximum number of a certain type of block. Using this, we would set the Hero Banner fieldset using `min: 1` and `max: 1`, and set the Contact Section simply with a `max: 1`.

This may be slightly more complex to implement, but is more flexible, and works nicely with the existing `limit:` option of the builder field: `limit:` would restrict the overall number of blocks, while `min` and `max` would control the number of specific block types. This would provide fine control of block numbers and type.

#### 3) Ultimate: add `max:` and `min:` to both fieldsets and builder field
To give _ultimate_ configuration flexibility, the current `limit:` option of the builder field - which is equivalent to a `max:` option - could be changed, so that at the field level itself we could also have `min:` and `max:` (instead of just `max:/limit:`). Using the example of the Landing Page above, this would allow me to specify that the Info Section should have at least 2 blocks - builder field's `min: 2` - and that one of these should be of a specific type - by setting a `min: 1` option in its fieldset.

**Comment by TimOetting** [comment]
Hey @luxlogica . This repo has been moved to https://github.com/TimOetting/kirby-builder . The limit option has been renamed to max. And, more important, the builder plugin now works with default values: You can add something like

```
...
label: My builder
type: builder
default: 
 - 
      text: My Hero Banner text
      _key: herobanner
...
```
This will add a predefined fieldset (in this case from the type herobanner) to any empty builder field as a starting point. You can still delete it but it would re-appear after the page reloads as long there is no other block created in the builder field. I will close this issue for now. If there is still need for blocks that can not be deleted, feel free to create another issue in the other repository
